title: 'DecaDojo - でかドージョー | プログラミングであそぼう！'
description: >-
  『でかドージョー』は近隣の CoderDojo が集まってプログラミングを楽しむお祭りです。
url:     'https://decadojo.coderdojo.jp'
baseurl: '/' # the subpath of your site, e.g. /blog
twitter_username: CoderDojoJapan
github_username:  coderdojo-japan

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Feed settings: https://github.com/jekyll/jekyll-feed
feed:
  path: /feed.xml
  posts_limit: 1000

exclude:
  - Rakefile

sass:
  style:     compressed
  sourcemap: always
