title: 'DecaDojo - でかドージョー | プログラミングであそぼう！'
description: >-
  『でかドージョー』は近隣の CoderDojo が集まってプログラミングを楽しむお祭りです。
url:     'https://decadojo.coderdojo.jp'
baseurl: '/' # the subpath of your site, e.g. /blog
twitter_username: CoderDojoJapan
github_username:  coderdojo-japan

# Build settings
theme: minima
plugins:
  - jekyll-feed

#exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
